//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/Input/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""OnFoot"",
            ""id"": ""ab9792b6-47c7-4fd1-9944-fadcab59bc8d"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""327b9a8b-94dc-4c3a-adcd-7b7e9bc155b3"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""719cb41b-8ce6-40f6-89a7-3fd220eb463f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""621dc4e7-d3ab-47db-97d8-7069b034c58b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Crouch"",
                    ""type"": ""Button"",
                    ""id"": ""cfb07ef1-76ce-46d9-9e62-33dc0f654c33"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SlowWalk"",
                    ""type"": ""Button"",
                    ""id"": ""c93ee351-d62d-4d56-962a-c8984643efbf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AttackPressed"",
                    ""type"": ""Button"",
                    ""id"": ""5eb66d2d-2cdd-4adf-bb79-866c4ab77d97"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AttackHold"",
                    ""type"": ""Button"",
                    ""id"": ""9c6f2d58-fd47-4ee2-b952-c3c00e1b5ae3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ADSPressed"",
                    ""type"": ""Button"",
                    ""id"": ""791f7fe6-5914-4277-90fe-146eb042b2c3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ADSReleased"",
                    ""type"": ""Button"",
                    ""id"": ""f904b882-bace-4329-adf3-2f13dfdc681c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ReloadPressed"",
                    ""type"": ""Button"",
                    ""id"": ""eb318639-60e5-41b6-976e-5d640963ff83"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EquipNextWeaponPressed"",
                    ""type"": ""Button"",
                    ""id"": ""aab11e9c-5d59-4d9c-a872-b1e246e178d6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EquipPreviousWeaponPressed"",
                    ""type"": ""Button"",
                    ""id"": ""08fc1cce-af94-4628-87c8-9d5a54a44e34"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EquipWeaponOnePressed"",
                    ""type"": ""Button"",
                    ""id"": ""34559633-515f-4db8-8f29-b5710d3dbcc3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EquipWeaponTwoPressed"",
                    ""type"": ""Button"",
                    ""id"": ""72f63924-3655-4b54-9766-9b44b46c1dae"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EquipFlashbangPressed"",
                    ""type"": ""Button"",
                    ""id"": ""ee552b60-50b4-41dd-905e-461cf0421b66"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""7887dd47-b36f-46f2-a467-cdb02ea5d9af"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""b009e26a-d86f-4228-afbe-27e4a1f1d329"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""e045cda3-dcee-4b89-b14e-963d992435bd"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""d72b3f46-b9dc-4a3e-b43c-d8c3b15f44e3"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""6830eec6-9b22-4fec-89ae-94ed43507009"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Left-Stick"",
                    ""id"": ""444b18c1-29b6-4682-855d-49f2c1cb64c9"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""0cf57481-1f91-431d-8fdd-e5f51d623248"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""6e0d68bd-f808-4eb3-8caa-68355b711297"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""c9680451-c4c3-415a-bba1-4eab01d56a87"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""028350b4-ad1b-4b3f-b0f7-fc3b282cbd94"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""17fb15e5-f956-4aab-8b9f-3031d23c92d5"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""433b29c4-57cb-4fc8-a011-b92360ef2db7"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c08e67ff-60ae-41d3-8f41-f61a1a300ab1"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e8456b3c-c79d-4d59-919f-dace83b687e9"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d9202dfa-ac04-4c69-b42c-50c88883cb4a"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c1948c5e-1220-415b-8b15-34bfad38ea61"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""89e0a6d1-98cd-4a2e-8e0a-612155391aa8"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SlowWalk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d8032bf8-0b45-49db-93c2-fd887d453253"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SlowWalk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""920f7040-297d-4f6c-a008-a1b2cbb8bce3"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AttackPressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d40a4761-e97d-4ae8-8455-e22cc041f218"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ADSPressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3e111e55-5afe-470e-a384-4b19d0e75d5e"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AttackHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cb82df59-1ae7-4e7d-b19c-ceac0eec805c"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ReloadPressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bb1054b1-fefa-41fa-aae1-246443d19a1e"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": ""Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ADSReleased"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""440541c5-d114-40ef-8832-be8e8b61a6a5"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EquipNextWeaponPressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b1e9bc58-07e1-4d0a-a856-bf5239944fdb"",
                    ""path"": ""<Keyboard>/capsLock"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EquipPreviousWeaponPressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""35e46b87-ced7-48e5-a905-1edde78e5d17"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EquipWeaponOnePressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""54be82f7-503a-47c9-9767-a27385f862c8"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EquipWeaponTwoPressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0e88e552-1a0f-4214-a3e3-400532924ee5"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EquipFlashbangPressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // OnFoot
        m_OnFoot = asset.FindActionMap("OnFoot", throwIfNotFound: true);
        m_OnFoot_Movement = m_OnFoot.FindAction("Movement", throwIfNotFound: true);
        m_OnFoot_Jump = m_OnFoot.FindAction("Jump", throwIfNotFound: true);
        m_OnFoot_Look = m_OnFoot.FindAction("Look", throwIfNotFound: true);
        m_OnFoot_Crouch = m_OnFoot.FindAction("Crouch", throwIfNotFound: true);
        m_OnFoot_SlowWalk = m_OnFoot.FindAction("SlowWalk", throwIfNotFound: true);
        m_OnFoot_AttackPressed = m_OnFoot.FindAction("AttackPressed", throwIfNotFound: true);
        m_OnFoot_AttackHold = m_OnFoot.FindAction("AttackHold", throwIfNotFound: true);
        m_OnFoot_ADSPressed = m_OnFoot.FindAction("ADSPressed", throwIfNotFound: true);
        m_OnFoot_ADSReleased = m_OnFoot.FindAction("ADSReleased", throwIfNotFound: true);
        m_OnFoot_ReloadPressed = m_OnFoot.FindAction("ReloadPressed", throwIfNotFound: true);
        m_OnFoot_EquipNextWeaponPressed = m_OnFoot.FindAction("EquipNextWeaponPressed", throwIfNotFound: true);
        m_OnFoot_EquipPreviousWeaponPressed = m_OnFoot.FindAction("EquipPreviousWeaponPressed", throwIfNotFound: true);
        m_OnFoot_EquipWeaponOnePressed = m_OnFoot.FindAction("EquipWeaponOnePressed", throwIfNotFound: true);
        m_OnFoot_EquipWeaponTwoPressed = m_OnFoot.FindAction("EquipWeaponTwoPressed", throwIfNotFound: true);
        m_OnFoot_EquipFlashbangPressed = m_OnFoot.FindAction("EquipFlashbangPressed", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // OnFoot
    private readonly InputActionMap m_OnFoot;
    private IOnFootActions m_OnFootActionsCallbackInterface;
    private readonly InputAction m_OnFoot_Movement;
    private readonly InputAction m_OnFoot_Jump;
    private readonly InputAction m_OnFoot_Look;
    private readonly InputAction m_OnFoot_Crouch;
    private readonly InputAction m_OnFoot_SlowWalk;
    private readonly InputAction m_OnFoot_AttackPressed;
    private readonly InputAction m_OnFoot_AttackHold;
    private readonly InputAction m_OnFoot_ADSPressed;
    private readonly InputAction m_OnFoot_ADSReleased;
    private readonly InputAction m_OnFoot_ReloadPressed;
    private readonly InputAction m_OnFoot_EquipNextWeaponPressed;
    private readonly InputAction m_OnFoot_EquipPreviousWeaponPressed;
    private readonly InputAction m_OnFoot_EquipWeaponOnePressed;
    private readonly InputAction m_OnFoot_EquipWeaponTwoPressed;
    private readonly InputAction m_OnFoot_EquipFlashbangPressed;
    public struct OnFootActions
    {
        private @PlayerInput m_Wrapper;
        public OnFootActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_OnFoot_Movement;
        public InputAction @Jump => m_Wrapper.m_OnFoot_Jump;
        public InputAction @Look => m_Wrapper.m_OnFoot_Look;
        public InputAction @Crouch => m_Wrapper.m_OnFoot_Crouch;
        public InputAction @SlowWalk => m_Wrapper.m_OnFoot_SlowWalk;
        public InputAction @AttackPressed => m_Wrapper.m_OnFoot_AttackPressed;
        public InputAction @AttackHold => m_Wrapper.m_OnFoot_AttackHold;
        public InputAction @ADSPressed => m_Wrapper.m_OnFoot_ADSPressed;
        public InputAction @ADSReleased => m_Wrapper.m_OnFoot_ADSReleased;
        public InputAction @ReloadPressed => m_Wrapper.m_OnFoot_ReloadPressed;
        public InputAction @EquipNextWeaponPressed => m_Wrapper.m_OnFoot_EquipNextWeaponPressed;
        public InputAction @EquipPreviousWeaponPressed => m_Wrapper.m_OnFoot_EquipPreviousWeaponPressed;
        public InputAction @EquipWeaponOnePressed => m_Wrapper.m_OnFoot_EquipWeaponOnePressed;
        public InputAction @EquipWeaponTwoPressed => m_Wrapper.m_OnFoot_EquipWeaponTwoPressed;
        public InputAction @EquipFlashbangPressed => m_Wrapper.m_OnFoot_EquipFlashbangPressed;
        public InputActionMap Get() { return m_Wrapper.m_OnFoot; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(OnFootActions set) { return set.Get(); }
        public void SetCallbacks(IOnFootActions instance)
        {
            if (m_Wrapper.m_OnFootActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnMovement;
                @Jump.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnJump;
                @Look.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnLook;
                @Look.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnLook;
                @Look.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnLook;
                @Crouch.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnCrouch;
                @Crouch.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnCrouch;
                @Crouch.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnCrouch;
                @SlowWalk.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnSlowWalk;
                @SlowWalk.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnSlowWalk;
                @SlowWalk.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnSlowWalk;
                @AttackPressed.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnAttackPressed;
                @AttackPressed.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnAttackPressed;
                @AttackPressed.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnAttackPressed;
                @AttackHold.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnAttackHold;
                @AttackHold.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnAttackHold;
                @AttackHold.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnAttackHold;
                @ADSPressed.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnADSPressed;
                @ADSPressed.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnADSPressed;
                @ADSPressed.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnADSPressed;
                @ADSReleased.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnADSReleased;
                @ADSReleased.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnADSReleased;
                @ADSReleased.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnADSReleased;
                @ReloadPressed.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnReloadPressed;
                @ReloadPressed.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnReloadPressed;
                @ReloadPressed.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnReloadPressed;
                @EquipNextWeaponPressed.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnEquipNextWeaponPressed;
                @EquipNextWeaponPressed.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnEquipNextWeaponPressed;
                @EquipNextWeaponPressed.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnEquipNextWeaponPressed;
                @EquipPreviousWeaponPressed.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnEquipPreviousWeaponPressed;
                @EquipPreviousWeaponPressed.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnEquipPreviousWeaponPressed;
                @EquipPreviousWeaponPressed.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnEquipPreviousWeaponPressed;
                @EquipWeaponOnePressed.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnEquipWeaponOnePressed;
                @EquipWeaponOnePressed.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnEquipWeaponOnePressed;
                @EquipWeaponOnePressed.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnEquipWeaponOnePressed;
                @EquipWeaponTwoPressed.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnEquipWeaponTwoPressed;
                @EquipWeaponTwoPressed.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnEquipWeaponTwoPressed;
                @EquipWeaponTwoPressed.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnEquipWeaponTwoPressed;
                @EquipFlashbangPressed.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnEquipFlashbangPressed;
                @EquipFlashbangPressed.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnEquipFlashbangPressed;
                @EquipFlashbangPressed.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnEquipFlashbangPressed;
            }
            m_Wrapper.m_OnFootActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Look.started += instance.OnLook;
                @Look.performed += instance.OnLook;
                @Look.canceled += instance.OnLook;
                @Crouch.started += instance.OnCrouch;
                @Crouch.performed += instance.OnCrouch;
                @Crouch.canceled += instance.OnCrouch;
                @SlowWalk.started += instance.OnSlowWalk;
                @SlowWalk.performed += instance.OnSlowWalk;
                @SlowWalk.canceled += instance.OnSlowWalk;
                @AttackPressed.started += instance.OnAttackPressed;
                @AttackPressed.performed += instance.OnAttackPressed;
                @AttackPressed.canceled += instance.OnAttackPressed;
                @AttackHold.started += instance.OnAttackHold;
                @AttackHold.performed += instance.OnAttackHold;
                @AttackHold.canceled += instance.OnAttackHold;
                @ADSPressed.started += instance.OnADSPressed;
                @ADSPressed.performed += instance.OnADSPressed;
                @ADSPressed.canceled += instance.OnADSPressed;
                @ADSReleased.started += instance.OnADSReleased;
                @ADSReleased.performed += instance.OnADSReleased;
                @ADSReleased.canceled += instance.OnADSReleased;
                @ReloadPressed.started += instance.OnReloadPressed;
                @ReloadPressed.performed += instance.OnReloadPressed;
                @ReloadPressed.canceled += instance.OnReloadPressed;
                @EquipNextWeaponPressed.started += instance.OnEquipNextWeaponPressed;
                @EquipNextWeaponPressed.performed += instance.OnEquipNextWeaponPressed;
                @EquipNextWeaponPressed.canceled += instance.OnEquipNextWeaponPressed;
                @EquipPreviousWeaponPressed.started += instance.OnEquipPreviousWeaponPressed;
                @EquipPreviousWeaponPressed.performed += instance.OnEquipPreviousWeaponPressed;
                @EquipPreviousWeaponPressed.canceled += instance.OnEquipPreviousWeaponPressed;
                @EquipWeaponOnePressed.started += instance.OnEquipWeaponOnePressed;
                @EquipWeaponOnePressed.performed += instance.OnEquipWeaponOnePressed;
                @EquipWeaponOnePressed.canceled += instance.OnEquipWeaponOnePressed;
                @EquipWeaponTwoPressed.started += instance.OnEquipWeaponTwoPressed;
                @EquipWeaponTwoPressed.performed += instance.OnEquipWeaponTwoPressed;
                @EquipWeaponTwoPressed.canceled += instance.OnEquipWeaponTwoPressed;
                @EquipFlashbangPressed.started += instance.OnEquipFlashbangPressed;
                @EquipFlashbangPressed.performed += instance.OnEquipFlashbangPressed;
                @EquipFlashbangPressed.canceled += instance.OnEquipFlashbangPressed;
            }
        }
    }
    public OnFootActions @OnFoot => new OnFootActions(this);
    public interface IOnFootActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnCrouch(InputAction.CallbackContext context);
        void OnSlowWalk(InputAction.CallbackContext context);
        void OnAttackPressed(InputAction.CallbackContext context);
        void OnAttackHold(InputAction.CallbackContext context);
        void OnADSPressed(InputAction.CallbackContext context);
        void OnADSReleased(InputAction.CallbackContext context);
        void OnReloadPressed(InputAction.CallbackContext context);
        void OnEquipNextWeaponPressed(InputAction.CallbackContext context);
        void OnEquipPreviousWeaponPressed(InputAction.CallbackContext context);
        void OnEquipWeaponOnePressed(InputAction.CallbackContext context);
        void OnEquipWeaponTwoPressed(InputAction.CallbackContext context);
        void OnEquipFlashbangPressed(InputAction.CallbackContext context);
    }
}
