//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/Input/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""OnFoot"",
            ""id"": ""ab9792b6-47c7-4fd1-9944-fadcab59bc8d"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""327b9a8b-94dc-4c3a-adcd-7b7e9bc155b3"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""719cb41b-8ce6-40f6-89a7-3fd220eb463f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""621dc4e7-d3ab-47db-97d8-7069b034c58b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Crouch"",
                    ""type"": ""Button"",
                    ""id"": ""cfb07ef1-76ce-46d9-9e62-33dc0f654c33"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SlowWalk"",
                    ""type"": ""Button"",
                    ""id"": ""c93ee351-d62d-4d56-962a-c8984643efbf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LowerXSensitivity"",
                    ""type"": ""Button"",
                    ""id"": ""d210cb0e-c7fd-47e2-83d3-e8cf90c35762"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RaiseXSensitivity"",
                    ""type"": ""Button"",
                    ""id"": ""2b72a68f-4b21-4b57-99ed-f90e93ec103e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AttackPressed"",
                    ""type"": ""Button"",
                    ""id"": ""75b531c2-9c8d-4f6f-aaf3-77a1dfe69a97"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AttackHold"",
                    ""type"": ""Button"",
                    ""id"": ""501de5ae-db77-4ff1-bfd9-5515f1a2c79a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ADSPressed"",
                    ""type"": ""Button"",
                    ""id"": ""142dc3c3-dd21-4225-9a71-28a97baa7c94"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ADSReleased"",
                    ""type"": ""Button"",
                    ""id"": ""2b7d9e1f-50ea-448d-aa3e-ad38d4804b9a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ReloadPressed"",
                    ""type"": ""Button"",
                    ""id"": ""074b5756-0042-4f71-b4c5-426a7f4bb525"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EquipNextWeaponPressed"",
                    ""type"": ""Button"",
                    ""id"": ""ea5c139c-45f5-4cf4-8e9a-866694aae197"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EquipPreviousWeaponPressed"",
                    ""type"": ""Button"",
                    ""id"": ""61d91a68-208c-466f-b427-6d9b57be7aa0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EquipWeaponOnePressed"",
                    ""type"": ""Button"",
                    ""id"": ""7e8f6cf0-e282-4cbb-aa72-b72eb63b97d7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EquipWeaponTwoPressed"",
                    ""type"": ""Button"",
                    ""id"": ""c74b8b8d-5c0e-49e4-871b-77748f107c36"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EquipFlashbangPressed"",
                    ""type"": ""Button"",
                    ""id"": ""ab18a52a-f3e7-499e-9d58-68feb6d8347e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Test_PlayerDamage"",
                    ""type"": ""Button"",
                    ""id"": ""def05250-eb13-41b5-b1be-ae4c7ea62c9c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""3561a37a-535f-4179-aa47-77a2384ede53"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HoldInteract"",
                    ""type"": ""Button"",
                    ""id"": ""3bab1baa-391f-4b48-b541-b9d5340a8d71"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PauseGame"",
                    ""type"": ""Button"",
                    ""id"": ""36e29e9a-13f0-4e2a-8dd0-990cc737619b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AttackReleased"",
                    ""type"": ""Button"",
                    ""id"": ""1562614f-deb4-451a-9365-2f14faf6fec1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""7887dd47-b36f-46f2-a467-cdb02ea5d9af"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""b009e26a-d86f-4228-afbe-27e4a1f1d329"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""e045cda3-dcee-4b89-b14e-963d992435bd"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""d72b3f46-b9dc-4a3e-b43c-d8c3b15f44e3"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""6830eec6-9b22-4fec-89ae-94ed43507009"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Left-Stick"",
                    ""id"": ""444b18c1-29b6-4682-855d-49f2c1cb64c9"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""0cf57481-1f91-431d-8fdd-e5f51d623248"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""6e0d68bd-f808-4eb3-8caa-68355b711297"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""c9680451-c4c3-415a-bba1-4eab01d56a87"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""028350b4-ad1b-4b3f-b0f7-fc3b282cbd94"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""17fb15e5-f956-4aab-8b9f-3031d23c92d5"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""433b29c4-57cb-4fc8-a011-b92360ef2db7"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c08e67ff-60ae-41d3-8f41-f61a1a300ab1"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e8456b3c-c79d-4d59-919f-dace83b687e9"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d9202dfa-ac04-4c69-b42c-50c88883cb4a"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c1948c5e-1220-415b-8b15-34bfad38ea61"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""89e0a6d1-98cd-4a2e-8e0a-612155391aa8"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SlowWalk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d8032bf8-0b45-49db-93c2-fd887d453253"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SlowWalk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cb894e42-77d1-4fc7-a4de-9a3807388774"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LowerXSensitivity"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""581d4473-2559-41cc-ae60-032ef2f3c901"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RaiseXSensitivity"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b4104256-e4c2-452e-b0bd-c7a408253ecd"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EquipWeaponOnePressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1a24f915-bf3e-4b8a-94d0-a5fed56a611e"",
                    ""path"": ""<Keyboard>/capsLock"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EquipPreviousWeaponPressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""82a96703-cc72-470f-9d84-86dfa908ad9d"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EquipNextWeaponPressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""77f9d16d-9f6a-481f-af65-061ce91a874f"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ReloadPressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a180f420-3ed5-4cdf-8ddb-0b5191a6cce6"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": ""Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ADSReleased"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""568a321a-0cd1-4103-807c-386a117a0d7e"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ADSPressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8e911afd-1bd7-441f-abb2-b9ded7e7f061"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AttackHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9e45efa4-bbfb-478f-9636-98a165aba84c"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AttackPressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""661014fd-ddd2-4e2f-8f0b-41a44ad72de7"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EquipFlashbangPressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""01907ea3-a787-419e-822c-b4d0b3b2bedd"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EquipWeaponTwoPressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""08316b3a-22f7-4efe-9a44-406c4fadea1c"",
                    ""path"": ""<Keyboard>/quote"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Test_PlayerDamage"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""598d117b-c8b2-41e1-af25-17faf38ee523"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""765c9e58-0d5d-4633-954f-66e4eecae1a6"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PauseGame"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5370f7f1-1a8d-410c-8e96-c14b142a5755"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": ""Hold(duration=3)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HoldInteract"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d443a1a0-b27c-4e92-aa10-be65f7194422"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AttackReleased"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // OnFoot
        m_OnFoot = asset.FindActionMap("OnFoot", throwIfNotFound: true);
        m_OnFoot_Movement = m_OnFoot.FindAction("Movement", throwIfNotFound: true);
        m_OnFoot_Jump = m_OnFoot.FindAction("Jump", throwIfNotFound: true);
        m_OnFoot_Look = m_OnFoot.FindAction("Look", throwIfNotFound: true);
        m_OnFoot_Crouch = m_OnFoot.FindAction("Crouch", throwIfNotFound: true);
        m_OnFoot_SlowWalk = m_OnFoot.FindAction("SlowWalk", throwIfNotFound: true);
        m_OnFoot_LowerXSensitivity = m_OnFoot.FindAction("LowerXSensitivity", throwIfNotFound: true);
        m_OnFoot_RaiseXSensitivity = m_OnFoot.FindAction("RaiseXSensitivity", throwIfNotFound: true);
        m_OnFoot_AttackPressed = m_OnFoot.FindAction("AttackPressed", throwIfNotFound: true);
        m_OnFoot_AttackHold = m_OnFoot.FindAction("AttackHold", throwIfNotFound: true);
        m_OnFoot_ADSPressed = m_OnFoot.FindAction("ADSPressed", throwIfNotFound: true);
        m_OnFoot_ADSReleased = m_OnFoot.FindAction("ADSReleased", throwIfNotFound: true);
        m_OnFoot_ReloadPressed = m_OnFoot.FindAction("ReloadPressed", throwIfNotFound: true);
        m_OnFoot_EquipNextWeaponPressed = m_OnFoot.FindAction("EquipNextWeaponPressed", throwIfNotFound: true);
        m_OnFoot_EquipPreviousWeaponPressed = m_OnFoot.FindAction("EquipPreviousWeaponPressed", throwIfNotFound: true);
        m_OnFoot_EquipWeaponOnePressed = m_OnFoot.FindAction("EquipWeaponOnePressed", throwIfNotFound: true);
        m_OnFoot_EquipWeaponTwoPressed = m_OnFoot.FindAction("EquipWeaponTwoPressed", throwIfNotFound: true);
        m_OnFoot_EquipFlashbangPressed = m_OnFoot.FindAction("EquipFlashbangPressed", throwIfNotFound: true);
        m_OnFoot_Test_PlayerDamage = m_OnFoot.FindAction("Test_PlayerDamage", throwIfNotFound: true);
        m_OnFoot_Interact = m_OnFoot.FindAction("Interact", throwIfNotFound: true);
        m_OnFoot_HoldInteract = m_OnFoot.FindAction("HoldInteract", throwIfNotFound: true);
        m_OnFoot_PauseGame = m_OnFoot.FindAction("PauseGame", throwIfNotFound: true);
        m_OnFoot_AttackReleased = m_OnFoot.FindAction("AttackReleased", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // OnFoot
    private readonly InputActionMap m_OnFoot;
    private IOnFootActions m_OnFootActionsCallbackInterface;
    private readonly InputAction m_OnFoot_Movement;
    private readonly InputAction m_OnFoot_Jump;
    private readonly InputAction m_OnFoot_Look;
    private readonly InputAction m_OnFoot_Crouch;
    private readonly InputAction m_OnFoot_SlowWalk;
    private readonly InputAction m_OnFoot_LowerXSensitivity;
    private readonly InputAction m_OnFoot_RaiseXSensitivity;
    private readonly InputAction m_OnFoot_AttackPressed;
    private readonly InputAction m_OnFoot_AttackHold;
    private readonly InputAction m_OnFoot_ADSPressed;
    private readonly InputAction m_OnFoot_ADSReleased;
    private readonly InputAction m_OnFoot_ReloadPressed;
    private readonly InputAction m_OnFoot_EquipNextWeaponPressed;
    private readonly InputAction m_OnFoot_EquipPreviousWeaponPressed;
    private readonly InputAction m_OnFoot_EquipWeaponOnePressed;
    private readonly InputAction m_OnFoot_EquipWeaponTwoPressed;
    private readonly InputAction m_OnFoot_EquipFlashbangPressed;
    private readonly InputAction m_OnFoot_Test_PlayerDamage;
    private readonly InputAction m_OnFoot_Interact;
    private readonly InputAction m_OnFoot_HoldInteract;
    private readonly InputAction m_OnFoot_PauseGame;
    private readonly InputAction m_OnFoot_AttackReleased;
    public struct OnFootActions
    {
        private @PlayerInput m_Wrapper;
        public OnFootActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_OnFoot_Movement;
        public InputAction @Jump => m_Wrapper.m_OnFoot_Jump;
        public InputAction @Look => m_Wrapper.m_OnFoot_Look;
        public InputAction @Crouch => m_Wrapper.m_OnFoot_Crouch;
        public InputAction @SlowWalk => m_Wrapper.m_OnFoot_SlowWalk;
        public InputAction @LowerXSensitivity => m_Wrapper.m_OnFoot_LowerXSensitivity;
        public InputAction @RaiseXSensitivity => m_Wrapper.m_OnFoot_RaiseXSensitivity;
        public InputAction @AttackPressed => m_Wrapper.m_OnFoot_AttackPressed;
        public InputAction @AttackHold => m_Wrapper.m_OnFoot_AttackHold;
        public InputAction @ADSPressed => m_Wrapper.m_OnFoot_ADSPressed;
        public InputAction @ADSReleased => m_Wrapper.m_OnFoot_ADSReleased;
        public InputAction @ReloadPressed => m_Wrapper.m_OnFoot_ReloadPressed;
        public InputAction @EquipNextWeaponPressed => m_Wrapper.m_OnFoot_EquipNextWeaponPressed;
        public InputAction @EquipPreviousWeaponPressed => m_Wrapper.m_OnFoot_EquipPreviousWeaponPressed;
        public InputAction @EquipWeaponOnePressed => m_Wrapper.m_OnFoot_EquipWeaponOnePressed;
        public InputAction @EquipWeaponTwoPressed => m_Wrapper.m_OnFoot_EquipWeaponTwoPressed;
        public InputAction @EquipFlashbangPressed => m_Wrapper.m_OnFoot_EquipFlashbangPressed;
        public InputAction @Test_PlayerDamage => m_Wrapper.m_OnFoot_Test_PlayerDamage;
        public InputAction @Interact => m_Wrapper.m_OnFoot_Interact;
        public InputAction @HoldInteract => m_Wrapper.m_OnFoot_HoldInteract;
        public InputAction @PauseGame => m_Wrapper.m_OnFoot_PauseGame;
        public InputAction @AttackReleased => m_Wrapper.m_OnFoot_AttackReleased;
        public InputActionMap Get() { return m_Wrapper.m_OnFoot; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(OnFootActions set) { return set.Get(); }
        public void SetCallbacks(IOnFootActions instance)
        {
            if (m_Wrapper.m_OnFootActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnMovement;
                @Jump.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnJump;
                @Look.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnLook;
                @Look.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnLook;
                @Look.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnLook;
                @Crouch.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnCrouch;
                @Crouch.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnCrouch;
                @Crouch.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnCrouch;
                @SlowWalk.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnSlowWalk;
                @SlowWalk.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnSlowWalk;
                @SlowWalk.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnSlowWalk;
                @LowerXSensitivity.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnLowerXSensitivity;
                @LowerXSensitivity.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnLowerXSensitivity;
                @LowerXSensitivity.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnLowerXSensitivity;
                @RaiseXSensitivity.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnRaiseXSensitivity;
                @RaiseXSensitivity.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnRaiseXSensitivity;
                @RaiseXSensitivity.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnRaiseXSensitivity;
                @AttackPressed.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnAttackPressed;
                @AttackPressed.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnAttackPressed;
                @AttackPressed.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnAttackPressed;
                @AttackHold.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnAttackHold;
                @AttackHold.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnAttackHold;
                @AttackHold.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnAttackHold;
                @ADSPressed.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnADSPressed;
                @ADSPressed.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnADSPressed;
                @ADSPressed.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnADSPressed;
                @ADSReleased.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnADSReleased;
                @ADSReleased.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnADSReleased;
                @ADSReleased.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnADSReleased;
                @ReloadPressed.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnReloadPressed;
                @ReloadPressed.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnReloadPressed;
                @ReloadPressed.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnReloadPressed;
                @EquipNextWeaponPressed.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnEquipNextWeaponPressed;
                @EquipNextWeaponPressed.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnEquipNextWeaponPressed;
                @EquipNextWeaponPressed.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnEquipNextWeaponPressed;
                @EquipPreviousWeaponPressed.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnEquipPreviousWeaponPressed;
                @EquipPreviousWeaponPressed.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnEquipPreviousWeaponPressed;
                @EquipPreviousWeaponPressed.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnEquipPreviousWeaponPressed;
                @EquipWeaponOnePressed.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnEquipWeaponOnePressed;
                @EquipWeaponOnePressed.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnEquipWeaponOnePressed;
                @EquipWeaponOnePressed.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnEquipWeaponOnePressed;
                @EquipWeaponTwoPressed.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnEquipWeaponTwoPressed;
                @EquipWeaponTwoPressed.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnEquipWeaponTwoPressed;
                @EquipWeaponTwoPressed.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnEquipWeaponTwoPressed;
                @EquipFlashbangPressed.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnEquipFlashbangPressed;
                @EquipFlashbangPressed.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnEquipFlashbangPressed;
                @EquipFlashbangPressed.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnEquipFlashbangPressed;
                @Test_PlayerDamage.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnTest_PlayerDamage;
                @Test_PlayerDamage.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnTest_PlayerDamage;
                @Test_PlayerDamage.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnTest_PlayerDamage;
                @Interact.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnInteract;
                @Interact.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnInteract;
                @Interact.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnInteract;
                @HoldInteract.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnHoldInteract;
                @HoldInteract.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnHoldInteract;
                @HoldInteract.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnHoldInteract;
                @PauseGame.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnPauseGame;
                @PauseGame.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnPauseGame;
                @PauseGame.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnPauseGame;
                @AttackReleased.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnAttackReleased;
                @AttackReleased.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnAttackReleased;
                @AttackReleased.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnAttackReleased;
            }
            m_Wrapper.m_OnFootActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Look.started += instance.OnLook;
                @Look.performed += instance.OnLook;
                @Look.canceled += instance.OnLook;
                @Crouch.started += instance.OnCrouch;
                @Crouch.performed += instance.OnCrouch;
                @Crouch.canceled += instance.OnCrouch;
                @SlowWalk.started += instance.OnSlowWalk;
                @SlowWalk.performed += instance.OnSlowWalk;
                @SlowWalk.canceled += instance.OnSlowWalk;
                @LowerXSensitivity.started += instance.OnLowerXSensitivity;
                @LowerXSensitivity.performed += instance.OnLowerXSensitivity;
                @LowerXSensitivity.canceled += instance.OnLowerXSensitivity;
                @RaiseXSensitivity.started += instance.OnRaiseXSensitivity;
                @RaiseXSensitivity.performed += instance.OnRaiseXSensitivity;
                @RaiseXSensitivity.canceled += instance.OnRaiseXSensitivity;
                @AttackPressed.started += instance.OnAttackPressed;
                @AttackPressed.performed += instance.OnAttackPressed;
                @AttackPressed.canceled += instance.OnAttackPressed;
                @AttackHold.started += instance.OnAttackHold;
                @AttackHold.performed += instance.OnAttackHold;
                @AttackHold.canceled += instance.OnAttackHold;
                @ADSPressed.started += instance.OnADSPressed;
                @ADSPressed.performed += instance.OnADSPressed;
                @ADSPressed.canceled += instance.OnADSPressed;
                @ADSReleased.started += instance.OnADSReleased;
                @ADSReleased.performed += instance.OnADSReleased;
                @ADSReleased.canceled += instance.OnADSReleased;
                @ReloadPressed.started += instance.OnReloadPressed;
                @ReloadPressed.performed += instance.OnReloadPressed;
                @ReloadPressed.canceled += instance.OnReloadPressed;
                @EquipNextWeaponPressed.started += instance.OnEquipNextWeaponPressed;
                @EquipNextWeaponPressed.performed += instance.OnEquipNextWeaponPressed;
                @EquipNextWeaponPressed.canceled += instance.OnEquipNextWeaponPressed;
                @EquipPreviousWeaponPressed.started += instance.OnEquipPreviousWeaponPressed;
                @EquipPreviousWeaponPressed.performed += instance.OnEquipPreviousWeaponPressed;
                @EquipPreviousWeaponPressed.canceled += instance.OnEquipPreviousWeaponPressed;
                @EquipWeaponOnePressed.started += instance.OnEquipWeaponOnePressed;
                @EquipWeaponOnePressed.performed += instance.OnEquipWeaponOnePressed;
                @EquipWeaponOnePressed.canceled += instance.OnEquipWeaponOnePressed;
                @EquipWeaponTwoPressed.started += instance.OnEquipWeaponTwoPressed;
                @EquipWeaponTwoPressed.performed += instance.OnEquipWeaponTwoPressed;
                @EquipWeaponTwoPressed.canceled += instance.OnEquipWeaponTwoPressed;
                @EquipFlashbangPressed.started += instance.OnEquipFlashbangPressed;
                @EquipFlashbangPressed.performed += instance.OnEquipFlashbangPressed;
                @EquipFlashbangPressed.canceled += instance.OnEquipFlashbangPressed;
                @Test_PlayerDamage.started += instance.OnTest_PlayerDamage;
                @Test_PlayerDamage.performed += instance.OnTest_PlayerDamage;
                @Test_PlayerDamage.canceled += instance.OnTest_PlayerDamage;
                @Interact.started += instance.OnInteract;
                @Interact.performed += instance.OnInteract;
                @Interact.canceled += instance.OnInteract;
                @HoldInteract.started += instance.OnHoldInteract;
                @HoldInteract.performed += instance.OnHoldInteract;
                @HoldInteract.canceled += instance.OnHoldInteract;
                @PauseGame.started += instance.OnPauseGame;
                @PauseGame.performed += instance.OnPauseGame;
                @PauseGame.canceled += instance.OnPauseGame;
                @AttackReleased.started += instance.OnAttackReleased;
                @AttackReleased.performed += instance.OnAttackReleased;
                @AttackReleased.canceled += instance.OnAttackReleased;
            }
        }
    }
    public OnFootActions @OnFoot => new OnFootActions(this);
    public interface IOnFootActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnCrouch(InputAction.CallbackContext context);
        void OnSlowWalk(InputAction.CallbackContext context);
        void OnLowerXSensitivity(InputAction.CallbackContext context);
        void OnRaiseXSensitivity(InputAction.CallbackContext context);
        void OnAttackPressed(InputAction.CallbackContext context);
        void OnAttackHold(InputAction.CallbackContext context);
        void OnADSPressed(InputAction.CallbackContext context);
        void OnADSReleased(InputAction.CallbackContext context);
        void OnReloadPressed(InputAction.CallbackContext context);
        void OnEquipNextWeaponPressed(InputAction.CallbackContext context);
        void OnEquipPreviousWeaponPressed(InputAction.CallbackContext context);
        void OnEquipWeaponOnePressed(InputAction.CallbackContext context);
        void OnEquipWeaponTwoPressed(InputAction.CallbackContext context);
        void OnEquipFlashbangPressed(InputAction.CallbackContext context);
        void OnTest_PlayerDamage(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnHoldInteract(InputAction.CallbackContext context);
        void OnPauseGame(InputAction.CallbackContext context);
        void OnAttackReleased(InputAction.CallbackContext context);
    }
}
